### PR TITLE
Results page inline tips 

### PR DESCRIPTION
**Pull request by orianaco**
All inline tips added to the results page apart from the carbon emissions one. Please test to see that the tips appear on hover as expected, and disappear once moving away from the orange text. 

A few comments/questions to address:
- If we are going ahead with an inline tip for carbon emissions, should we make the words "carbon emissions" orange?
- The tooltip on "25 year" was causing me some issues - please check to see if it opens normally, or if you really have to find the right spot for it to open up.... I found it to be the latter, and not really sure how to address this issue.
- Comment on the Inline Tip doc if you have any ideas for copy changes, this can still easily be done, so no worries (https://docs.google.com/document/d/1t9KUMNiUMDvy642H2aWlO57WPgIg0NHT55EQTxBnr-A/edit) 
- Is the arrow at the top large enough? I made it a bit bigger than what we had on the start savings page, but had issues enlarging it any further than what is is. To me it looks alright though.

Let me know if there is anything else you notice as well :)

### CODE REVIEW

**Comment by gmalekan** [comment]
@orianaco great work on this oc! For the most parts it look good but I did have some comment:

- having the additional words in the burnt orange does not look great and look very random on the page.. I would suggest reverting "25 year" and "carbon emissions" back to black and if possible just making the inline help tip appear the user hovers over the whole block of text not just the specific works. I do think that just like the other ones users will discover there is a hover state on their own
- The 25 year savings tip is a bit hard to activate at times, seems like you need to go over it from a certain position to get it to work. Maybe activating the whole block of text might fix this issue
- the carbon reduction help tip is not appearing for me either, I know Tanushree suggested a fix so not sure if that was any help in resolving this issue

Let me know if you have any questions about the comments.

**Comment by gmalekan** [comment]
@orianaco oh also i think there is an extra space between "over" and "25 year" would be great if you can remove that :)

**Comment by orianaco** [comment]
hi @gmalekan thanks for the feedback. this actually made things easier in terms of the tips popping up properly!
they should all be appearing as expected now, however I did notice that the environmental impact section seems way too close to the content below now. I'm not sure what happened.... but can I move that whole section down a bit?

Screen Shot 2021-03-23 at 12 45 58 PM

**Comment by gmalekan** [comment]
@orianaco yesss the tips appear a lot easier now! I also see the what you're saying about the env section, but i think the carbon text shifted upwards not the section heading, because the tree planting side looks right. 

Another small thing i noticed is that the carbon tip seems to have more padding around the text compared to others, if this is something that can be fixed, that would be great.
Screen Shot 2021-03-23 at 1 39 44 PM

Other than these two small things, everything looks great and you'll be good to merge!

**Comment by orianaco** [comment]
@gmalekan good catch on the padding, it did look a bit larger so I decreased it a tad. Also moved the carbon emissions text down and well as the # of metric tonnes. let me know if this looks good to go now. thanks!

**Review by gmalekan — APPROVED** [review]

**Pull request merged**
