### PR TITLE
checking postal codes against our df

### PR DESCRIPTION
**Pull request by toni-li**
Ticket: https://jira.uwaterloo.ca/browse/SOLI-50

Added a check to see if the user inputted postal code is in the array of postal codes that we have in our array.

An error message is now generated within the default value(s) pop-up to prompt the user to use a neighbouring postal code or continue with our default postal code of M5W.

Feedback Requested:
1. Check to see if the pop-up is working as expected.
2. The title of this default value(s) pop-up is Incomplete Field(s) which is fine when we're using the default values for if a user leaves an input field blank but isn't super accurate if they've just entered a postal code that's not in our array. In the case where that's the only default value being used, we can change the title to be something like "Default Postal Code Used", but in the case that the postal code default is being used AND other default values are being used, is it ok to keep the title as "Incomplete Field(s)" or should we also change that to reflect the default postal code being used? 

I feel like point 2 is confusing, so please message me if you don't understand what I'm trying to say.

### CODE REVIEW

**Comment by orianaco** [comment]
Hi Toni,

The pop-up is working as expected, nice job. I don't think it is a problem to leave the title as "Incomplete fields" so long as there are other incomplete fields. I would agree with you in that we should use a diff title to reflect that the postal code is not in our DB if the postal code is the only field in question, and is of the correct format. 

I would like to suggest a wording change though, let me know what you think:

"The postal code entered is not in Ontario. Please update with a neighbouring postal code, or a default code from Toronto (M5W) will be used."

**Comment by toni-li** [comment]
Hi Oriana,

Great, I can make that title change for if the only error is that the postal code is not in our array. What do you think of the title of "Default Postal Code Used" for that case? I'm open to suggestions...you're the creative writer here :) 

I like your edits to the error text, my only concern is what if the postal code they entered is within Ontario and it's just not in our array? Can we be 100% sure that the postal codes that we have included in our array cover all of Ontario? Also, even if they do, what if a new postal code is added? Not sure how often that happens so maybe that's not something we need to worry about? 

Toni

**Comment by orianaco** [comment]
Hi @toni-li ,

apologies for the late response, I did not see your comment :( 

I think a clearer title might just be "Invalid Postal Code" and then go on to explain that we will use the default. 
In terms of if the postal code is not in our array, I was under the impression that we got all the postal codes for Ontario. Maybe double check with Ghazal. Good point about new ones being added though - I tried to search up how often they were updated, but couldn't find too much. We could say:

"The postal code entered is not in Ontario as of 2020. Please update with a neighbouring postal code, or a default code from Toronto (M5W) will be used."

Not sure what you think about that ?
OC

**Comment by toni-li** [comment]
@orianaco please check out the latest changes. 

The copy was updated for the titles depending on what error is occurring and the copy for the default postal code error message was modified to be "The postal code entered cannot be found in Ontario as of 2020. Please update with a neighbouring postal code, or a default postal code from Toronto (M5W) will be used.".

Toni

**Comment by orianaco** [comment]
@toni-li  Just checked this out, and it looks good - I think youre good to merge!

**Pull request merged**
