### PR TITLE
Form Page Fields

### PR DESCRIPTION
**Pull request by orianaco**
**Created the Solar and Solar + Battery pages based on [SOLI-12 ticket](https://jira.uwaterloo.ca/browse/SOLI-12)** 

**There are still some updates that need to be completed:**
 - Dropdowns for applicable fields (currently labels)
 - Budget button increasing and decreasing based on user action (currently a normal label)
 - Resize the page to remove additional white space at the bottom
 - Include footer

**Feedback requests:**
- Overall font size and spacing on page -- it's not aligned exactly as it is in Figma due to the wider page space we have now
- Is the question mark image of good enough quality? (I made it in draw.io )
- Is the "Generate Results" button too large? For now I thought I'd keep it consistent with the "Start Savings" button but I think it could be smaller

Additionally, I changed all but one case of "px" in the css file to the corresponding "vh" or "vw" size. The one outstanding is in the Sticky class and needs to be changed to a % still. Please note if there are any others that I missed.

### CODE REVIEW

**Comment by toni-li** [comment]
Hi Oriana,

Great work on this PR, the form is looking pretty sweet. I think the quality of the question mark circles are good enough so I don't think you need to revise them. 

There are a couple of things that I think should be changed. 
1. I think the text size of the middle column of labels (Postal Code, Roof Size, etc.) and size of the input boxes can be bigger. Currently it looks a little out of balance with the size of the left column labels and the text above the form.
2. The middle column labels and the text boxes aren't lined up with the main label for Home Specs and Initial Investment 
2. I think that the generate button is a bit large, but I think that increasing the size of the font of the form might help that balance? If not, feel free to reduce the size of the button.
3. The changes that you made to the CSS to make sure everything is in vw/vh/% look good to me except for the footer which I think could be moved down a little.

As for your list of things that you still need to do, we already have a ticket in the backlog for the footer thing so you don't have to worry about that. 

Let me know if you have any questions or need any help with the updates.

Toni

**Comment by tanushree-sharma** [comment]
Hi Oriana,

The form looks great so far!

Heres some feedback: 

- I think the size you have for the fields (postal code, roof size..etc) should be the smallest our font goes. I would suggest starting off with that size for the smallest text you currently have and then working up from there. 
- The quality of the question mark looks good to me
- The button does look a bit big, but I think that when the font size for the rest of the form is increased, the button will look more proportional

BTW - I just merged my PR for adding the python backend in so you will have to resolve conflicts that before merging. [This](https://opensource.com/article/20/4/git-merge-conflict) is a good resource with steps on how to resolve but if you need help let me know. 

Awesome work OC

**Comment by toni-li** [comment]
Hi Oriana,

The additions of the dropdowns and +/- buttons look great! 

There are some things that need to be modified:
- The month label (id month-title) isn't centered with the energy usage label. It's currently at 89% but I think 88.3% looks more centered.
- The placeholder text doesn't resize when the size of the window is resized. I think you should be able to add a font-size line to the css of the placeholder text to have it based on the vh. 
- There's the same issue with the text on the +/- buttons where it's not resizing with the window
Screen Shot 2021-02-03 at 9 28 44 PM


Other than these small things, the PR looks good! 

Toni

**Comment by orianaco** [comment]
Hey @tanushree-sharma @gmalekan @toni-li  :) 

Thank you for your initial input on the forms page from my commit yesterday.
While the page is still not 100% complete, some more progress has been made as listed below:

1. Updates to the page alignment / sizing of the elements. I increased all the text and input fields by the same factor -- let me know if this looks balanced now and/or if it is large enough for the page. 

2. I'm beginning to think our choice of grey for the outline of our input fields might be too light. On my laptop screen it seems okay, but when using my monitor it is very faint. Please take a look on your laptop and monitors and comment on if you think it's worth darkening. I included a screenshot of what it would look like using our darker grey, but I don't love it.

3. Dropdowns added for the _Month_ and _Type of Heating_ parameters. Some things to consider:
    - Do you like or dislike the "Select month/heating" as the placeholder value for the dropdowns? This is not what is in Figma 
     but seems like best practice based on some examples I looked at. 
    **TO-DO**
    - The "select month/heating" option should disappear once the user opens the dropdown
    - When the user selects an option, it should appear un-italicized in darker text 

4. Budget
    - What do you think of the grey buttons, and white overlay when hovering? I played around with a couple different options, 
     but thought this worked nicely. Open to other colour/shading options though!
    **TO-DO**
    - The $ sign at the beginning of the input (this will be the same thing as the % infront of DoD that also needs to be 
       added
    - The line separating the +/- (if we still want it)
    

Look forward to hearing what you guys think! Sorry this ticket is not quite complete, but I'm still learning so it's taking me a loooong time. Big shoutout to @toni-li for helping me with a couple things on this ticket today too!

OC

**Comment by toni-li** [comment]
Hi Oriana,

The additions of the dropdowns and +/- buttons look great! To answer your questions:
1. The increases in font size look good to me. There is one label that is still not centered. The month label (id month-title) isn't centered with the energy usage label. It's currently at 89% but I think 88.3% looks better.
2. I agree that the outline of the textboxes look a bit too light. Somewhere in between the light grey that we have and the grey that you included in your screenshot would work, but if that's not possible, I think that the dark grey is fine.
3. The select month/heating placeholder text makes sense to me. Good call on looking at other examples to get best practices. On the note of placeholder text though, I've noticed that it doesn't resize with the resizing of the window. I think you should be able to add a font-size line to the css of the placeholder text to have it based on the vh.
4. I really like what you've done with the budget buttons and the white overlay. I think the buttons look fine when the window is resized but the text inside the buttons need to be scaled down as well. Currently, the buttons are resizing but not the text which makes the text float outside of the buttons when the screen gets smaller.
Screen Shot 2021-02-03 at 9 40 51 PM

Other than that, please comment out or remove the imported packages that you haven't used ("react-dropdown-select") because they are causing problems when I try to run your branch.

It looks like there are still a few stylistic things that need to be fixed or added but overall you've done an A1 job. This ticket was a big one but you've crushed it, mate! I think that if needed we should be able to go ahead and merge this version into main so that Tan and Ghazal can start on their tickets while you work on the style changes. We should clear this with the git expert (@tanushree-sharma) before we do this though...

Toni

**Comment by tanushree-sharma** [comment]
The form functionality is shaping up well, great job Oriana and Toni. 

The only point of feedback that I have from the things you mentioned is that I still think the font size could be increased, its a bit on the smaller side for some elements. But not a huge deal so we can discuss potentially increasing it later. Other than that and the TO-DOs you've mentioned, everything looks good as is to me. 

I'm going to fix conflicts and merge this into main.

**Pull request merged**
