### PR TITLE
Results graph

### PR DESCRIPTION
**Pull request by tanushree-sharma**
[Ticket](https://jira.uwaterloo.ca/secure/RapidBoard.jspa?rapidView=515&projectKey=SOLI&view=detail&selectedIssue=SOLI-30)

**Testing:** 
- Test out graph back and forth functionality
- Print costsWithoutSolar and costsWithSolar on both solarModel.py and solarBatteryModel.py and verify results are displayed correctly on graph

**Notes:**
- The y axis labels of the graph floats and I'm unable to make it so that it has a white background on top of the bars
- On load of the graph, year 0 gets cut off and it isn't until you click/hover over the graph that it appears. I tried to fix this but then started running into issues with the y axis labels getting cut off so I think this is as good as it gets

### CODE REVIEW

**Comment by orianaco** [comment]
Hi @tanushree-sharma ,

Overall this feature looks really cool - nice work!

Here are my comments:
- The back and forth functionality works well for me, only thing I noticed like you pointed out was the issue with the y-axis, but I don't think that's a huge deal. 
- I think the issue you mentioned with year 0 not showing right away is okay - as soon as you hover it appears
- The axis titles are both off centre and I think definitely need to be centred. I also think the space between the x-axis and "Year" can be reduced.
- Add a $ after the "Cost" axis title 
-  I'm not sure "Cost Savings with Solar" is the most approp. title, since we don't actually give them the number that they are saving each year, but rather the cost of with and without. I have an idea for this that I can share tomorrow, but maybe it's too much work.
- I'm not sure users will get that they can scroll through the years, since there is no indication of this. Perhaps some arrows at the bottom may make it clearer. I know we had that scroll bar in the Figmas, but maybe its just a static arrow that says scroll for more years or something (obvi not that).

I still need to test out printing the results from the .py files - currently having backend issues so will take a look again later.

**Comment by tanushree-sharma** [comment]
Thanks for taking a look! I'd love to hear your thoughts on the title tomorrow, I was having a hard time thinking of an appropriate one. 

I've made the changes you suggested and attached a screenshot so you don't need to run the code again. Lmk what you think
image

**Comment by orianaco** [comment]
@tanushree-sharma , I like the changes! I just think now we could use a bit more space between the axes and the titles haha.

Also, just tested the numbers on the graph against what is printing in the code and it all looks good!

**Comment by tanushree-sharma** [comment]
Okay, I added more space. Going to merge.

**Pull request merged**
