### PR TITLE
Forms font updates (final!!! hopefully) + footer edits

### PR DESCRIPTION
**Pull request by orianaco**
Hello @gmalekan ,
Please take a look at the edits to the forms page... I think that I've reached a happy medium that I like with respect to the font sizes, but let me know what you think!

Some other files were also changed, as I switched the Copyright year to 2021. I was wondering if you had a moment to please look at the footer on the Start Savings page. I  tried to do it like the results page, but was having issues with it because it was not reaching the width of the full page (just the width of the form). Maybe something I can talk to @toni-li  about as well, because she set-up this page. 

Also, I fixed the issue where the default values in the dropdown for the Solar form were still in black (on Chrome, that is haha)
Thanks!

### CODE REVIEW

**Comment by toni-li** [comment]
Hi @orianaco,

I'm not seeing a footer on the starts savings page so I'm not sure what you mean by it was not reaching the width of the full page...

Toni

**Comment by toni-li** [comment]
Hi @orianaco,

I'm happy to say I think we've changed the size of these inputs for the last time! I am satisfied with the size of this font as it looks like a good medium between the last update and the original font size. 

As for the footer, I noticed that you wrote the footer instead of importing the component. To keep consistent with our other pages, I think it's best to use the imported component. 

To do so, you can just remove everything inside the first div of class "footer-ss" and replace it with <Footer />. To fix the issue that you were seeing with the footer not reaching the full width of the page, you can just modify the css for this class and add a left element with a negative % value. I think Left: -10%; might be close to what you're looking for. I think that you should also modify the top value because the footer is currently resting right at the bottom of the page whereas the footer on the main page has a bit of space between the footer and the bottom of the page. 

I know the results page footer is squished at the bottom but there's a ticket in the backlog to fix that. 

Toni

**Comment by orianaco** [comment]
Hi @toni-li , thanks for those tips - very helpful! 

-11.75% seemed like the magic number to me, but if you'd like to take a look and make sure it looks okay on your end, that would be great.

Cheers,
Oriana

**Comment by toni-li** [comment]
@orianaco - can you modify the top value of the footer as well so it's not sticking at the bottom of the page? I've attached a screenshot of the homepage footer for reference. 

Screen Shot 2021-02-24 at 4 16 34 PM

After that change, you should be good to merge!

**Pull request merged**
