### PR TITLE
Minor updates to forms pages

### PR DESCRIPTION
**Pull request by orianaco**
Hey guys,

I've made most of the updates to the forms pages as discussed last week now. Here they are listed below:

- Drop downs no longer show the "select month/heating" as a selectable option
- $ and % are added to the appropriate fields 
- Lines beside $ and % are also added (imo they are a bit too thick, but I can't seem to decrease the thickness lol)
- User input appears in Mulish font after they enter it

To-Do:
- Make the value in the drop downs normal, black font once they are selected (I was struggling with this, so if anyone has any suggestions / knows how to do it, please let me know!)
- IDK if my eyes are going a bit wonky but the yellow ?'s look like they're not perfect circles... perhaps a resizing issue, but I feel like they look different than when I had them in last.
- Potentially increase font sizes - but I think it looks fine on a laptop sized screen 

 Look forward to hearing what you guys think :)

### CODE REVIEW

**Comment by toni-li** [comment]
Hi Oriana,

Here's my feedback:
- The smallest that a border can go is 1px so I don't think you'll be able to decrease the lines beside the $ and %. Given this constraint, I would suggest we get rid of the divider lines. 
- The Month subtitle is not lined up with the Energy Usage title. I think it needs to be moved up by 0.5-1% on both the Solar and Solar+Battery form. 
- For consistency with the field inputs, I think that the dropdown options should all be in black font, not just when one is selected. In my opinion, in the input fields, the only text that should be grey are the placeholders. This should be easily done for the field inputs, but for the dropdowns, you'll probably have to assign the first option values a class and have that class have the grey font color. 
- The yellow ?'s look fine to me.
- I think that the font size of the subtitles (middle column) should be slightly bigger, maybe 1.15vw.
- The placeholder text should be representative of the default values that we'll be using. Specifically, the Electricity Usage should be something closer to 750 and Storage Capacity being something like 13.
- I've noticed that the input placeholder text and the +/- buttons don't scale well when the screen resizes (see screenshot), but this might have to be something that we log as a bug and come back to since I don't foresee users trying to fill in this form with the window so small lol
Screen Shot 2021-02-10 at 9 52 58 PM

Let me know if you have any questions or need any help!

**Comment by orianaco** [comment]
Hi @toni-li ,

Thanks for reviewing the page. I have a couple comments based on your feedback:
- I agree that we can get rid of the divider lines, but want to wait for confirmation from @gmalekan and @tanushree-sharma before doing that 
- I moved the Energy Usage title slightly down, it should align with the Month title now
- Wrt the dropdown inputs, I've changed the "Select month" and "Select heating" to be black and normal font, that makes sense. I don't get what you mean by having the placeholder value grey for the drop downs though, because currently the "Select month" and "Select heating" acts as the placeholder. I'm not sure how we will make it clear what specific default we will be using if nothing is selected...not sure this is too important though, as we do tell them we'll be using defaults at the top.
- Good catch on the placeholder values - I updated them based on your suggestion, and we can change them again if needed.
- I'll open a ticket for resizing issues with the budget +/- buttons. The text in the dropdowns could use some resizing help too.

**Comment by toni-li** [comment]
@orianaco 

I meant keeping all the placeholder text + "Select month" and "Select heating" in the grey and having the options under the dropdowns (Jan, Feb, etc.) be black. So on load, the inputs fields should have grey text, and once a user types or selects their input, the text should be black. 

I hope that makes sense, if not I'm happy to hop on a call to explain what I mean.

**Comment by tanushree-sharma** [comment]
Hi Oriana,

I've taken a look and here are some of my thoughts:

- I'm good to get rid of the divider lines
- I agree with what Toni is saying in having  "Select month" and "Select heating" in grey so that its consistent with the rest of the fields
- I think the font size of the last 2 columns needs to be increased. It's hard to read and looks especially small when compared to the font sizes on the home page and results page. We can put a ticket in and fix it later, no need to tackle in this ticket
- The circles are different than what you had before. I changed them when I was doing the help tips, they are no longer images. When we increase the font size we should also scale the size of these up accordingly
- Looking at the Month dropdown - I suggest getting rid of the month numbers. Its a bit clunky and I don't see what purpose they serve for the user

**Comment by gmalekan** [comment]
@orianaco I agree with getting rid of the divider and greying out those two placeholders. I am somewhat indifferent about other changes so I'll leave it to the rest of you to figure that out as long as things look good. Overall great work on the fixes!

**Pull request merged**
