### PR TITLE
Error handling on forms page

### PR DESCRIPTION
**Pull request by toni-li**
Ticket: https://jira.uwaterloo.ca/browse/SOLI-31

Two-step error handling was implemented by adding a visual indication of valid inputs on each input box and a consolidated error message with all the errors on hover of the generate results button. The input boxes should highlight in yellow when the input is valid. When the input is not valid, the border will be grey and the Generate Results button will be disabled. When the user hovers over the Generate Results button, a pop-up will show with all the fixes that the user needs to make. 

The following error handling methods were implemented:
Postal Code
- Max input length of 3 characters
- Make sure inputs are in the form of a letter - number - letter

Roof Size
- Input is numerical
- Input is greater than the size of one panel (~20 soft)

Electricity Usage
- Input is numerical
- Input is greater than the output of one solar panel per month (52kWh)

Month
- No checks implemented since the user is limited to selecting valid values

Type of Heating
- No checks implemented since the user is limited to selecting valid values

Storage Capacity
- Input is numerical
- Input is greater than 0 kWh

Depth of Discharge
- Input is numerical
- Input is greater than 0%

Budget
- Input is numerical
- Input is greater than the cost of one panel + fixed costs which is $3500

Requested Feedback:
- Make sure all the error handling that I’ve highlighted above is working as expected
- Double check my calculation to get the minimum Electricity Usage of 52

### CODE REVIEW

**Comment by tanushree-sharma** [comment]
Hey Toni,

Thanks for the thorough work! Looks good to merge...jkjk see my feedback below

I've validated each of your error handling checks. Here are some things we need to change:
**Postal Code**
This isn't mentioned on Jira, but we also need to validate that the postal code entered is in our system and if not, let the user know they can update it or we will use a default
**Roof Size**
I noticed that when I input values from 20-47 the results page shows all zeros. I believe this is due to the Armax = (Ar / 2) * 0.8 calculation that is used in our roof constraint. We can round this up and set the lower limit to 50 instead of 20. 
**Electricity Usage**
I noticed that when I input values from 52-118 and the month is set to April, the results page shows all zeros. I this could be due to the energy usage forecasting. We will need to play around with the diff months to figure out what the actual lower limit is. 
**Depth of Discharge**
Also need to restrict this so it is less than 100%

General thoughts:
- After trying out the system with the input checking for the lower bounds, I wonder if this is actually even necessary. I'd like to discuss it at the meeting today but I added feedback anyway in the case that we keep it
- I love the yellow outline that is used to validate input. Is it possible to highlight the input boxes with invalid input in burnt orange?
- Why did you decide to do error checking on hover of the generate results button vs on click of the button? I think it is a clever way to do error checking, however from a user perspective it was unexpected and I would be more comfortable with an on-click error checking. 

Cheers,
Tanushree

**Comment by toni-li** [comment]
Hey Tan,

Thanks for the thorough review :)

Good point on the postal code thing. I think that this check might work better with the default inputs pop-up because it's not an actual error that will break our model, just something that we should notify the user of. 

I can limit the depth of discharge to be between 0-100, that was an oversight on my part 👎 

I agree that the on hover trigger of the invalid inputs modal is unexpected from a user standpoint. The reason why this was done is to keep the consistency between the default values modal which is triggered by an on hover. The default inputs modal is triggered by an on hover to check for empty values on the frontend instead of having to send the empty values to the backend to be checked and then sent back to the front end in the form of a page reload. I reckon we'll get some feedback on this during our walkthroughs so if users are having a hard time with the functionality, I'm open to figuring out a workaround. 

I'll hold off on implementing the other feedback until after our discussions today.

Toni

**Comment by tanushree-sharma** [comment]
You're right the on hover is a good place for user feedback. I'm good with keeping that as is for now.

**Comment by toni-li** [comment]
@tanushree-sharma 

Here are the changes that I've made based on our discussions:
- highlight invalid values in burnt orange
- set lower bounds to be 0
- moved the Invalid Input(s) title down

Please take a look and let me know if there was anything that I missed.

Toni

**Comment by tanushree-sharma** [comment]
I loove the burnt orange for invalid inputs! Error handling functionality works well. 

I'd like to point out some visuals that I think need to be fixed:
- The navbar doesn't get greyed out when the error message is shown
- The diamond with ! is not centered on the error message 

image

**Comment by toni-li** [comment]
@tanushree-sharma 
The warning image should now be centered within the modal. 

I've sent you a text about greying out the nav bar when the modal shows up but just to mention it here as well, I tried to add the greyed out feature to the nav bar but since the nav bar is placed on top of other components on the page, making it greyed out / transparent means that you can see through the navbar and see the components of the forms page behind it which looks funny. 
Screen Shot 2021-02-19 at 11 59 52 AM

I'm not sure how else we would do this feature without using transparency, so I'm inclined to leave it as is, but if you really don't like it then I could potentially find a work around...

**Comment by tanushree-sharma** [comment]
No worries, I dont think the navbar not being greyed out is a big deal. 

Looks good to merge!

**Pull request merged**
