### PR TITLE
Adding underline on the nav bar

### PR DESCRIPTION
**Pull request by toni-li**
Testing:
- click on the different nav bar options to make sure underline is showing up only on the active item
- click the logo to make sure it redirects to the home page

### CODE REVIEW

**Comment by tanushree-sharma** [comment]
Hey Toni,

Functionality works well. Making the logo redirect home is a good touch. 

The design of the underline isn't exactly what was mocked in the Figmas, but I like this too! @orianaco @gmalekan what are your thoughts on sticking with the way Toni coded it?

image

**Comment by gmalekan** [comment]
@toni-li @tanushree-sharma hm yea it's a bit different but i think it's good enough. Maybe if we increase the weight of the line y just a bit it might be better? it looks a bit think in the pic

**Comment by toni-li** [comment]
Ok, checkout the updates. 

I've made the line thicker and make it the same size for all of the nav bar options.

**Comment by gmalekan** [comment]
@toni-li good to merge. great job!

**Pull request merged**
