### PR TITLE
Integration of the models to the front end

### PR DESCRIPTION
**Pull request by toni-li**
Completed integration of the frontend and backend. 

Inputted values on the forms page are now passed into the models and returned back to the front end in the form of the optimal number of watts to install. 

Testing: (make sure to yarn run start-api lol) 
- same testing as we did for the model development (ex. varying inputs, keeping the inputs the same between the two models, and seeing if there's a difference in the optimal value)
- compare results from running just the models to the results when running the models through the front end

Things to Note:
- there is no error handling on the form yet so if you enter in wack values it'll break
- the rendered template with the optimal values is rendering the whole js file instead of just the HTML part for some reason but I figured we could convert that results page into an HTML page and just import the js that we need for downloading the page as a pdf. Not sure if that's the best solution so if anyone else has any ideas, lmk!

### CODE REVIEW

**Comment by tanushree-sharma** [comment]
Hey Toni,

Great job! This is working for me, looks good to merge. 

I'm not sure what you mean by "the rendered template with the optimal values is rendering the whole js file instead of just the HTML".  Could you clarify?

**Comment by toni-li** [comment]
The template that is currently being rendered by the flask backend is a .js files like the other components of our webapp. When the model is called and values are served (idk if that's the right use of the word lol) to the frontend, the results page shows import statements from the .js file that are not in between the <div> tags.
Screen Shot 2021-02-05 at 6 14 47 PM

I only have experience with rendering an HTML template with flask so I was thinking we could just make results.js into results.html but I'm not sure if that'll cause other issues because all the other components of our webapp are .js.

**Comment by tanushree-sharma** [comment]
Ah I see what you're saying. The text on the top is coming from the About.js file which is so weird. Taking a look at the Flask documentation, it seems like you can only render .html files. I agree that creating a results.html file and adding js into there is the best route. 

For the purposes of this PR, the stuff you have is good to merge. 

Btw, Ghazal was having some issues running the code so she's unable to review this PR.

**Comment by toni-li** [comment]
Ok, I'll change it to an html file type and merge.

Thanks, Tan! :)

**Pull request merged**
