### PR TITLE
Results page

### PR DESCRIPTION
**Pull request by toni-li**
Added results page components. 

Test out different inputs to see if the page scales well when the results change.

Things still to do:
- add graph
- for some reason, I couldn't figure out how to get images to show up...

### CODE REVIEW

**Comment by gmalekan** [comment]
@toni-li woah good just getting all this done so quick! Most of the components look great there are just a few edits that need to be made which I've listed below.

**Edits:**
- Add a bit more space between the titles "installation size", "initial investment", "payback period", and "over 25-year time horizon" and the numbers above them (just by 1-2% maybe so it's not squished)
- The Spring and Fall title/numbers should not be going out of the margins for the Savings section
Screen Shot 2021-02-08 at 11 26 14 AM

- The Environmental Impact title seems to be going into a second line even though it has a lot of space in front of it. I might be because of the placeholder image of the graph thats pushing it down but it would be great if it's just one line
- Also, the number of tree plantings seems to be going into the text, and i think it's because you might tested it out with a smaller number so now there's not enough space for it. Not sure exactly what we can do about this considering the length of the text there is going to vary... 
Screen Shot 2021-02-08 at 11 28 09 AM

- I think we're having a similar problems as last time with the excess horizontal scroll on the page which makes it look like the results section isn't centred on the page
Screen Shot 2021-02-08 at 11 31 17 AM


Sorry I know that was a lot, feel free to create separate tickets if they're more difficult fixes rather than quick edits.

**Comment by toni-li** [comment]
Hi Ghazaloo, 

Thanks for taking such an in-depth look at my PR. I've made the change you've suggested so please take a look to make sure they're good to go. 

I wasn't seeing the same issue that you were having with the wrapping of the Recommended System Specs and Environmental Impact titles, but I've widened the div and enabled "nowrap" so hopefully, it'll all stay on one line.

Toni

**Comment by gmalekan** [comment]
@toni-li Everything looks great, thanks for making those changes! I do find that some of the problems are Safari or Chrome specific so might be different when we're viewing them.

I know you mentioned changing the label for the cost to "initial investment" so you can go ahead with that and then you should be good to merge :)

**Comment by toni-li** [comment]
Oh right, I forgot you're a safari user 🙄🙄🙄

I'll go ahead and make that last change and merge. 

Thanks!

**Comment by gmalekan** [comment]
How can you be an iCal user but not a Safari user???

Also, i noticed some issues on other pages but went ahead and added them as bugs to deal with later so don't worry about them if you see anything weird. If it's something new feel free to add a ticket for it.

**Pull request merged**
