### PR TITLE
linking results page to results faq section with new copy

### PR DESCRIPTION
**Pull request by toni-li**
Ticket: https://jira.uwaterloo.ca/browse/SOLI-73

Added link from the results page to FAQ page for users who want more information on how their results are calculated. 

Please make sure that the hyperlink is opening up a new tab and going straight to the results section of the FAQ page. 
Also, read over the copy to make sure everything makes sense.

### CODE REVIEW

**Comment by orianaco** [comment]
Hi @toni-li this is looking good and the link to the FAQ page works as expected, and opens up right into the results section.

I do have a couple of suggestions that I think might help with how the updated FAQ section looks:

- Maybe we use arrows (→ ) instead of colons after each of the subsections. This would keep things consistent with the pros and cons section.
- If we switch to arrows, then add colons to the main headers (recommended system specs, savings, etc.). If we keep as is, then 'Payback Period' needs a colon. 
- Recommended System Specifications is still in need of an 's' :( 
- I think the subsections need to be scooted in a bit more - play around with it and see what looks better but I want to say around 5 more space bars or so. This will probably make it easier to read. 
- What do we think about changing the "click here" text to be burnt orange? Maybe this could be a nice touch since the other parts that are orange on the page are hoverable. Not too important though!

**Comment by toni-li** [comment]
@orianaco thanks for the feedback! Please checkout the changes :)

**Comment by orianaco** [comment]
@toni-li  ooooh I am here for the burnt orange "click here" yay!
Changes look good - I think maybe the sub sections could still be further indented, but def better than before, and maybe if we indent any further the text will be too chunky cause it will spill onto more lines?

I think you're good to merge :)

**Comment by gmalekan** [comment]
@toni-li @orianaco i know this PR wasn't assigned to me but i did have some comments hehe. Overall looks really good and i am here for the burnt orange link! 

- the faq part is in need of some more breaks between the headings/section, it's kinda really smushed together and hard to read right now
- for the description of the installation size i would yeet the part about multiplying number of panels by capacity and say that your inputs are run through Soli's optimization model which factors in the details you provided and recommends optimal installation sides that can best satisfy your energy demand
- would be nice if you can add more space between the text added on the results page and the buttons below it
- wondering if we need to make the text on results page bigger or somehow more prominent? I just think it might be easy to miss on the page with everything on there, lmk what you think.

**Comment by gmalekan** [comment]
@toni-li sorry to butt in again but on another note i noticed that the spacing between sections on the faq page is not the same, not sure if it looks like that just for me
Screen Shot 2021-03-21 at 8 06 33 PM

**Comment by gmalekan** [comment]
@toni-li @orianaco ok last thing (pls don't hate me) 
The way we did the formatting for an answer with multiple sections is different and it's best to keep it the same (see picture) i think it's good to indent the sub-sections but keep the headers aligned with the question text
Screen Shot 2021-03-21 at 8 11 34 PM

**Comment by toni-li** [comment]
@orianaco @gmalekan pls take a look at the changes :)

**Comment by orianaco** [comment]
@toni-li changes look good to me, but am a bit unsure about the yellow block bar at the bottom hmmmm... what if we make it a blue or yellow underline similar to how the tops of the forms and results pages are ?

Or also I, noticed in Figma that the mockup Ghazal did has the bar stretch to the entire width of the screen which I think looks better, but in the coded version it doesn't. 


Screen Shot 2021-03-23 at 12 53 29 PM

**Comment by toni-li** [comment]
@orianaco yes I noticed that Ghazal's figma mock-up had the bar extended to the full width of the page, but since the page orientation is different on the actual results page, it looks funny with the bar extended all the way.

**Review by orianaco — APPROVED** [review]

**Pull request merged**
